import { CrosshairIcon, HouseIcon, ListStarIcon, MedalIcon, NotebookIcon, TrophyIcon } from "@phosphor-icons/react";


export default [
  { label: 'Utama' },
  {
    href: '/tatib/panel',
    label: 'Home',
    icon: (<HouseIcon weight='regular' className='text-[22px] sm:text-xl' />),
    backroundColor: 'bg-sky-500/10',
    checkIsActive: (pathNames: string[]) => [undefined, '', 'akun'].includes(pathNames[3]),
  },
  {
    href: '/tatib/panel/portofolio-non-akademik',
    label: 'Portofolio Siswa',
    icon: (<TrophyIcon weight='regular' className='text-[22px] sm:text-xl' />),
    backroundColor: 'bg-sky-500/10',
    checkIsActive: (pathNames: string[]) => 'portofolio-non-akademik' == pathNames[3],
    featureCodes: [],
    essentialPaths: [],
    groupMenu: '',
  },
  {
    href: '/tatib/panel/pelanggaran',
    label: 'Pelanggaran',
    icon: (<CrosshairIcon weight='regular' className='text-[22px] sm:text-xl' />),
    backroundColor: 'bg-sky-500/10',
    checkIsActive: (pathNames: string[]) => ['pelanggaran', 'peraturan'].includes(pathNames[3]),
    featureCodes: [],
    essentialPaths: [],
    groupMenu: 'pelanggaran',
  },
  {
    href: '/tatib/panel/penghargaan',
    label: 'Penghargaan',
    icon: (<MedalIcon weight='regular' className='text-[22px] sm:text-xl' />),
    backroundColor: 'bg-sky-500/10',
    checkIsActive: (pathNames: string[]) => ['penghargaan', 'jenis-penghargaan'].includes(pathNames[3]),
    featureCodes: [],
    essentialPaths: [],
    groupMenu: 'penghargaan',
  },
  {
    label: "Master Data",
  },
  {
    href: '/tatib/panel/peraturan',
    label: 'Peraturan Sekolah',
    icon: (<NotebookIcon weight='regular' className='text-[22px] sm:text-xl' />),
    backroundColor: 'bg-sky-500/10',
    checkIsActive: (pathNames: string[]) => 'peraturan' == pathNames[3],
    featureCodes: [],
    essentialPaths: [],
    groupMenu: 'pelanggaran',
  },
  {
    href: '/tatib/panel/jenis-penghargaan',
    label: 'Jenis Penghargaan',
    icon: (<ListStarIcon weight='regular' className='text-[22px] sm:text-xl' />),
    backroundColor: 'bg-sky-500/10',
    checkIsActive: (pathNames: string[]) => 'jenis-penghargaan' == pathNames[3],
    featureCodes: [],
    essentialPaths: [],
    groupMenu: 'penghargaan',
  },
] as typeMenuApps